services:
    CleverAge\EnqueueProcessBundle\Subscriber\ProcessTopicConsumer:
        autowire: true
        public: true # Required for enqueue
        tags:
        # Tags will be added dynamically from configuration

    CleverAge\EnqueueProcessBundle\Subscriber\ProcessCommandConsumer:
        autowire: true
        public: true
        # Tags will be added dynamically from configuration
