services:
    CleverAge\EnqueueProcessBundle\Subscriber\ProcessConsumer:
        autowire: true
        public: true # Required for enqueue
        tags:
            - { name: enqueue.client.processor }
